view(iris)
c<-table(iris$Species)
barplot(c,xlab = 'species',main='bar chart',legend=rownames(c),col = c('red','yellow','green'))
library(plotrix)
pie(c,col=rainbow(5))
hist(iris$Sepal.Length,col='dark green')
plot(density(iris$Sepal.Length),main='density plot')
polygon(density(iris$Sepal.Length),col='sky blue',border = 'black')
plot(iris$Petal.Length,iris$Petal.Width,type = 'p')
summary(iris$Sepal.Width)
boxplot(iris$Sepal.Width)
